alias ga='git add'
alias gc='git commit --allow-empty-message -m "."'
alias gd='git diff'
alias gg='ga .gitignore KATA-LOG LESSON_LEARNED TODO aliases.sh *cpp anki/mem.csv; gc; gp'
alias gp='git push -u origin master'
alias gs='git status'
alias kata='kata_file $(random_kata); subl a.cpp &'
