alias gp='git push -u origin master'
alias gc='git commit --allow-empty-message -m ""'
alias ga='git add'
alias gd='git diff'
alias gs='git status'
alias g='git'
alias gg='ga *cpp; gc; gp'

alias ff='ls -l'
alias f='ls'
alias q='cd ..'
alias n='nano'
